export interface Product {
  id: string;
  name: string;
  slug: string;
  category: string;
  benefit: string;
  ingredients: string[];
  price: number;
  originalPrice: number;
  discount: number;
  rating: number;
  reviewCount: number;
  badge: 'New' | 'Bestseller' | 'Limited' | null;
  image: string;
  healthGoals: string[];
  productType: string;
  dietPreference: string[];
  availability: 'In Stock' | 'Low Stock' | 'Out of Stock';
}

export const CATEGORIES = [
  'All',
  'Immunity',
  'Digestive Wellness',
  'Hair Care',
  'Skin Care',
  'Stress Relief',
  "Women's Wellness",
  'Kids',
] as const;

export type Category = (typeof CATEGORIES)[number];

export const SORT_OPTIONS = [
  { value: 'featured', label: 'Featured' },
  { value: 'price-asc', label: 'Price: Low to High' },
  { value: 'price-desc', label: 'Price: High to Low' },
  { value: 'rating', label: 'Highest Rated' },
  { value: 'newest', label: 'Newest First' },
] as const;

export const HEALTH_GOALS = [
  'Boost Immunity',
  'Improve Digestion',
  'Reduce Stress',
  'Healthy Hair',
  'Glowing Skin',
  'Better Sleep',
  'Energy & Vitality',
  'Hormonal Balance',
  'Joint Health',
  'Detox',
];

export const PRODUCT_TYPES = [
  'Capsules',
  'Powder',
  'Oil',
  'Serum',
  'Syrup',
  'Tea',
  'Tablets',
  'Cream',
];

export const DIET_PREFERENCES = [
  'Vegan',
  'Vegetarian',
  'Gluten-Free',
  'Sugar-Free',
  'Organic',
];

export const BENEFITS = [
  'Anti-Inflammatory',
  'Antioxidant Rich',
  'Adaptogenic',
  'Probiotic',
  'High Bioavailability',
  'Clinically Studied',
];

export const products: Product[] = [
  {
    id: 'p1',
    name: 'Ashwagandha KSM-66',
    slug: 'ashwagandha-ksm66',
    category: 'Immunity',
    benefit: 'Reduces stress & strengthens natural immunity',
    ingredients: ['Ashwagandha', 'Black Pepper', 'Ginger'],
    price: 799,
    originalPrice: 999,
    discount: 20,
    rating: 4.8,
    reviewCount: 1247,
    badge: 'Bestseller',
    image: 'https://images.unsplash.com/photo-1611241893603-3c228ee8f71c?w=600&h=600&fit=crop&q=80',
    healthGoals: ['Boost Immunity', 'Reduce Stress', 'Energy & Vitality'],
    productType: 'Capsules',
    dietPreference: ['Vegan', 'Gluten-Free', 'Organic'],
    availability: 'In Stock',
  },
  {
    id: 'p2',
    name: 'Golden Turmeric Elixir',
    slug: 'golden-turmeric-elixir',
    category: 'Immunity',
    benefit: 'Powerful anti-inflammatory with curcumin complex',
    ingredients: ['Turmeric', 'Curcumin', 'Piperine'],
    price: 649,
    originalPrice: 849,
    discount: 24,
    rating: 4.7,
    reviewCount: 893,
    badge: 'New',
    image: 'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=600&h=600&fit=crop&q=80',
    healthGoals: ['Boost Immunity', 'Joint Health', 'Detox'],
    productType: 'Capsules',
    dietPreference: ['Vegan', 'Gluten-Free'],
    availability: 'In Stock',
  },
  {
    id: 'p3',
    name: 'Chyawanprash Gold',
    slug: 'chyawanprash-gold',
    category: 'Immunity',
    benefit: 'Ancient immunity rasayana with 48 herbs',
    ingredients: ['Amla', 'Giloy', 'Pippali'],
    price: 549,
    originalPrice: 699,
    discount: 21,
    rating: 4.9,
    reviewCount: 2104,
    badge: 'Bestseller',
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&h=600&fit=crop&q=80',
    healthGoals: ['Boost Immunity', 'Energy & Vitality', 'Detox'],
    productType: 'Syrup',
    dietPreference: ['Vegetarian', 'Gluten-Free'],
    availability: 'In Stock',
  },
  {
    id: 'p4',
    name: 'Triphala Digestive Complex',
    slug: 'triphala-digestive-complex',
    category: 'Digestive Wellness',
    benefit: 'Gentle daily detox for digestive harmony',
    ingredients: ['Haritaki', 'Bibhitaki', 'Amalaki'],
    price: 449,
    originalPrice: 599,
    discount: 25,
    rating: 4.6,
    reviewCount: 756,
    badge: null,
    image: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=600&h=600&fit=crop&q=80',
    healthGoals: ['Improve Digestion', 'Detox'],
    productType: 'Tablets',
    dietPreference: ['Vegan', 'Gluten-Free', 'Organic'],
    availability: 'In Stock',
  },
  {
    id: 'p5',
    name: 'Digestive Fire Churna',
    slug: 'digestive-fire-churna',
    category: 'Digestive Wellness',
    benefit: 'Activates agni for optimal nutrient absorption',
    ingredients: ['Ginger', 'Cumin', 'Fennel'],
    price: 349,
    originalPrice: 449,
    discount: 22,
    rating: 4.5,
    reviewCount: 432,
    badge: 'New',
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&h=600&fit=crop&q=80',
    healthGoals: ['Improve Digestion', 'Detox', 'Energy & Vitality'],
    productType: 'Powder',
    dietPreference: ['Vegan', 'Gluten-Free', 'Sugar-Free'],
    availability: 'In Stock',
  },
  {
    id: 'p6',
    name: 'Gut Restore Probiotic',
    slug: 'gut-restore-probiotic',
    category: 'Digestive Wellness',
    benefit: 'Balances gut flora with Ayurvedic probiotics',
    ingredients: ['Triphala', 'Licorice', 'Cardamom'],
    price: 899,
    originalPrice: 1099,
    discount: 18,
    rating: 4.7,
    reviewCount: 621,
    badge: null,
    image: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?w=600&h=600&fit=crop&q=80',
    healthGoals: ['Improve Digestion', 'Boost Immunity'],
    productType: 'Capsules',
    dietPreference: ['Vegetarian', 'Gluten-Free'],
    availability: 'Low Stock',
  },
  {
    id: 'p7',
    name: 'Bhringraj Hair Vitality Oil',
    slug: 'bhringraj-hair-vitality-oil',
    category: 'Hair Care',
    benefit: 'Prevents hair fall & promotes thick growth',
    ingredients: ['Bhringraj', 'Amla', 'Coconut Oil'],
    price: 599,
    originalPrice: 749,
    discount: 20,
    rating: 4.8,
    reviewCount: 1893,
    badge: 'Bestseller',
    image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600&h=600&fit=crop&q=80',
    healthGoals: ['Healthy Hair'],
    productType: 'Oil',
    dietPreference: ['Vegan', 'Organic'],
    availability: 'In Stock',
  },
  {
    id: 'p8',
    name: 'Keratin Herbal Shampoo',
    slug: 'keratin-herbal-shampoo',
    category: 'Hair Care',
    benefit: 'Sulfate-free cleansing with herbal keratin',
    ingredients: ['Shikakai', 'Reetha', 'Hibiscus'],
    price: 449,
    originalPrice: 549,
    discount: 18,
    rating: 4.4,
    reviewCount: 567,
    badge: null,
    image: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=600&h=600&fit=crop&q=80',
    healthGoals: ['Healthy Hair'],
    productType: 'Cream',
    dietPreference: ['Vegan', 'Organic'],
    availability: 'In Stock',
  },
  {
    id: 'p9',
    name: 'Hair Growth Capsules',
    slug: 'hair-growth-capsules',
    category: 'Hair Care',
    benefit: 'Biotin & Ayurvedic herbs for internal nourishment',
    ingredients: ['Bhringraj', 'Brahmi', 'Iron'],
    price: 699,
    originalPrice: 899,
    discount: 22,
    rating: 4.6,
    reviewCount: 934,
    badge: 'New',
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&h=600&fit=crop&q=80',
    healthGoals: ['Healthy Hair', 'Energy & Vitality'],
    productType: 'Capsules',
    dietPreference: ['Vegetarian', 'Gluten-Free'],
    availability: 'In Stock',
  },
  {
    id: 'p10',
    name: 'Kumkumadi Radiance Serum',
    slug: 'kumkumadi-radiance-serum',
    category: 'Skin Care',
    benefit: 'Brightens skin with precious saffron extract',
    ingredients: ['Saffron', 'Sandalwood', 'Lotus'],
    price: 1299,
    originalPrice: 1599,
    discount: 19,
    rating: 4.9,
    reviewCount: 1456,
    badge: 'Bestseller',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&h=600&fit=crop&q=80',
    healthGoals: ['Glowing Skin'],
    productType: 'Serum',
    dietPreference: ['Vegan', 'Organic'],
    availability: 'In Stock',
  },
  {
    id: 'p11',
    name: 'Rose Glow Face Mist',
    slug: 'rose-glow-face-mist',
    category: 'Skin Care',
    benefit: 'Hydrating toner with pure rose distillate',
    ingredients: ['Rose', 'Aloe Vera', 'Glycerin'],
    price: 399,
    originalPrice: 499,
    discount: 20,
    rating: 4.5,
    reviewCount: 823,
    badge: null,
    image: 'https://images.unsplash.com/photo-1601049676869-702ea24cfd58?w=600&h=600&fit=crop&q=80',
    healthGoals: ['Glowing Skin'],
    productType: 'Serum',
    dietPreference: ['Vegan', 'Organic'],
    availability: 'In Stock',
  },
  {
    id: 'p12',
    name: 'Neem Purifying Face Wash',
    slug: 'neem-purifying-face-wash',
    category: 'Skin Care',
    benefit: 'Deep cleanses pores & controls excess oil',
    ingredients: ['Neem', 'Tea Tree', 'Tulsi'],
    price: 349,
    originalPrice: 449,
    discount: 22,
    rating: 4.3,
    reviewCount: 412,
    badge: null,
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&h=600&fit=crop&q=80',
    healthGoals: ['Glowing Skin', 'Detox'],
    productType: 'Cream',
    dietPreference: ['Vegan', 'Organic'],
    availability: 'In Stock',
  },
  {
    id: 'p13',
    name: 'Brahmi Mind Calm',
    slug: 'brahmi-mind-calm',
    category: 'Stress Relief',
    benefit: 'Sharpens focus while calming the nervous system',
    ingredients: ['Brahmi', 'Shankhpushpi', 'Jatamansi'],
    price: 599,
    originalPrice: 749,
    discount: 20,
    rating: 4.7,
    reviewCount: 678,
    badge: null,
    image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=600&h=600&fit=crop&q=80',
    healthGoals: ['Reduce Stress', 'Better Sleep'],
    productType: 'Capsules',
    dietPreference: ['Vegan', 'Gluten-Free'],
    availability: 'In Stock',
  },
  {
    id: 'p14',
    name: 'Sleep Deep Elixir',
    slug: 'sleep-deep-elixir',
    category: 'Stress Relief',
    benefit: 'Promotes restful sleep without morning grogginess',
    ingredients: ['Ashwagandha', 'Tagara', 'Chamomile'],
    price: 749,
    originalPrice: 949,
    discount: 21,
    rating: 4.8,
    reviewCount: 1102,
    badge: 'Bestseller',
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&h=600&fit=crop&q=80',
    healthGoals: ['Better Sleep', 'Reduce Stress'],
    productType: 'Syrup',
    dietPreference: ['Vegetarian', 'Sugar-Free'],
    availability: 'In Stock',
  },
  {
    id: 'p15',
    name: 'Calm & Balance Tea',
    slug: 'calm-balance-tea',
    category: 'Stress Relief',
    benefit: 'Soothing herbal blend for daily tranquility',
    ingredients: ['Tulsi', 'Lavender', 'Lemon Balm'],
    price: 299,
    originalPrice: 399,
    discount: 25,
    rating: 4.6,
    reviewCount: 534,
    badge: 'New',
    image: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=600&h=600&fit=crop&q=80',
    healthGoals: ['Reduce Stress', 'Better Sleep', 'Detox'],
    productType: 'Tea',
    dietPreference: ['Vegan', 'Gluten-Free', 'Sugar-Free', 'Organic'],
    availability: 'In Stock',
  },
  {
    id: 'p16',
    name: 'Shatavari Women\'s Tonic',
    slug: 'shatavari-womens-tonic',
    category: "Women's Wellness",
    benefit: 'Supports hormonal balance & reproductive health',
    ingredients: ['Shatavari', 'Lodhra', 'Ashoka'],
    price: 849,
    originalPrice: 1099,
    discount: 23,
    rating: 4.8,
    reviewCount: 967,
    badge: 'Bestseller',
    image: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&h=600&fit=crop&q=80',
    healthGoals: ['Hormonal Balance', 'Energy & Vitality'],
    productType: 'Capsules',
    dietPreference: ['Vegetarian', 'Gluten-Free'],
    availability: 'In Stock',
  },
  {
    id: 'p17',
    name: 'Iron & Vitality Plus',
    slug: 'iron-vitality-plus',
    category: "Women's Wellness",
    benefit: 'Plant-based iron with enhanced absorption',
    ingredients: ['Moringa', 'Amla', 'Beetroot'],
    price: 549,
    originalPrice: 699,
    discount: 21,
    rating: 4.5,
    reviewCount: 445,
    badge: null,
    image: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=600&h=600&fit=crop&q=80',
    healthGoals: ['Energy & Vitality', 'Hormonal Balance'],
    productType: 'Tablets',
    dietPreference: ['Vegan', 'Gluten-Free', 'Organic'],
    availability: 'In Stock',
  },
  {
    id: 'p18',
    name: 'PMS Comfort Blend',
    slug: 'pms-comfort-blend',
    category: "Women's Wellness",
    benefit: 'Eases menstrual discomfort naturally',
    ingredients: ['Ashoka', 'Dashmool', 'Ginger'],
    price: 649,
    originalPrice: 799,
    discount: 19,
    rating: 4.6,
    reviewCount: 389,
    badge: 'New',
    image: 'https://images.unsplash.com/photo-1556228841-a3c527ebefe5?w=600&h=600&fit=crop&q=80',
    healthGoals: ['Hormonal Balance', 'Reduce Stress'],
    productType: 'Capsules',
    dietPreference: ['Vegetarian', 'Gluten-Free'],
    availability: 'Low Stock',
  },
  {
    id: 'p19',
    name: 'Kids Immunity Gummies',
    slug: 'kids-immunity-gummies',
    category: 'Kids',
    benefit: 'Tasty herbal gummies kids love for daily immunity',
    ingredients: ['Amla', 'Giloy', 'Honey'],
    price: 499,
    originalPrice: 599,
    discount: 17,
    rating: 4.9,
    reviewCount: 1567,
    badge: 'Bestseller',
    image: 'https://images.unsplash.com/photo-1584308666982-507400f30aaf?w=600&h=600&fit=crop&q=80',
    healthGoals: ['Boost Immunity', 'Energy & Vitality'],
    productType: 'Tablets',
    dietPreference: ['Vegetarian', 'Gluten-Free'],
    availability: 'In Stock',
  },
  {
    id: 'p20',
    name: 'Kids Brain Booster',
    slug: 'kids-brain-booster',
    category: 'Kids',
    benefit: 'Enhances memory & concentration for young minds',
    ingredients: ['Brahmi', 'Shankhpushpi', 'Almonds'],
    price: 549,
    originalPrice: 699,
    discount: 21,
    rating: 4.7,
    reviewCount: 823,
    badge: null,
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&h=600&fit=crop&q=80',
    healthGoals: ['Reduce Stress', 'Energy & Vitality'],
    productType: 'Syrup',
    dietPreference: ['Vegetarian'],
    availability: 'In Stock',
  },
  {
    id: 'p21',
    name: 'Giloy Immunity Drops',
    slug: 'giloy-immunity-drops',
    category: 'Immunity',
    benefit: 'Concentrated guduchi extract for daily defense',
    ingredients: ['Giloy', 'Tulsi', 'Neem'],
    price: 399,
    originalPrice: 499,
    discount: 20,
    rating: 4.5,
    reviewCount: 612,
    badge: null,
    image: 'https://images.unsplash.com/photo-1585232352617-51f5119dd6ef?w=600&h=600&fit=crop&q=80',
    healthGoals: ['Boost Immunity', 'Detox'],
    productType: 'Syrup',
    dietPreference: ['Vegan', 'Gluten-Free', 'Sugar-Free'],
    availability: 'In Stock',
  },
  {
    id: 'p22',
    name: 'Joint Ease Formula',
    slug: 'joint-ease-formula',
    category: 'Immunity',
    benefit: 'Supports joint mobility & reduces inflammation',
    ingredients: ['Boswellia', 'Guggulu', 'Nirgundi'],
    price: 899,
    originalPrice: 1199,
    discount: 25,
    rating: 4.6,
    reviewCount: 534,
    badge: 'Limited',
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=600&h=600&fit=crop&q=80',
    healthGoals: ['Joint Health', 'Boost Immunity'],
    productType: 'Tablets',
    dietPreference: ['Vegetarian', 'Gluten-Free'],
    availability: 'Low Stock',
  },
  {
    id: 'p23',
    name: 'Aloe Vera Skin Gel',
    slug: 'aloe-vera-skin-gel',
    category: 'Skin Care',
    benefit: 'Pure aloe gel for soothing & hydration',
    ingredients: ['Aloe Vera', 'Vitamin E', 'Cucumber'],
    price: 299,
    originalPrice: 399,
    discount: 25,
    rating: 4.4,
    reviewCount: 723,
    badge: null,
    image: 'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600&h=600&fit=crop&q=80',
    healthGoals: ['Glowing Skin'],
    productType: 'Cream',
    dietPreference: ['Vegan', 'Organic'],
    availability: 'In Stock',
  },
  {
    id: 'p24',
    name: 'Kids Growth Milk Mix',
    slug: 'kids-growth-milk-mix',
    category: 'Kids',
    benefit: 'Herbal milk mix for healthy growth & strong bones',
    ingredients: ['Ashwagandha', 'Shatavari', 'Calcium'],
    price: 449,
    originalPrice: 549,
    discount: 18,
    rating: 4.6,
    reviewCount: 678,
    badge: 'New',
    image: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=600&h=600&fit=crop&q=80',
    healthGoals: ['Boost Immunity', 'Energy & Vitality'],
    productType: 'Powder',
    dietPreference: ['Vegetarian', 'Gluten-Free'],
    availability: 'In Stock',
  },
];
